version: '3.8'
services:
  supabase-db:
    image: supabase/postgres:14.1.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Tiger1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  supabase-studio:
    image: supabase/studio:latest    # Changed to latest tag
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: Tiger1234
      DEFAULT_ORGANIZATION: OctoSoft
      DEFAULT_PROJECT: crm

  kong:
    image: kong:2.8.1
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
    volumes:
      - ./kong.yml:/var/lib/kong/kong.yml:ro

  meta:
    image: supabase/postgres-meta:v0.68.0
    ports:
      - "8080:8080"
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: supabase-db
      PG_META_DB_PASSWORD: Tiger1234
      